// This file is autogenerated. Do not modify
package controllers

import (
	"errors"
	"log"
	"net/http"

	gosnappi "github.com/open-traffic-generator/snappi/gosnappi"
	"github.com/open-traffic-generator/snappi/gosnappi/httpapi"
	"github.com/open-traffic-generator/snappi/gosnappi/httpapi/interfaces"
)

type capabilitiesController struct {
	handler interfaces.CapabilitiesHandler
}

func NewHttpCapabilitiesController(handler interfaces.CapabilitiesHandler) interfaces.CapabilitiesController {
	return &capabilitiesController{handler}
}

func (ctrl *capabilitiesController) Routes() []httpapi.Route {
	return []httpapi.Route{
		{Path: "/capabilities/version", Method: "GET", Name: "GetVersion", Handler: ctrl.GetVersion},
	}
}

/*
GetVersion: GET /capabilities/version
Description:
*/
func (ctrl *capabilitiesController) GetVersion(w http.ResponseWriter, r *http.Request) {
	result := ctrl.handler.GetVersion(r)
	if result.HasStatusCode200() {
		if _, err := httpapi.WriteJSONResponse(w, 200, result.StatusCode200()); err != nil {
			log.Print(err.Error())
		}
		return
	}
	if result.HasStatusCode400() {
		if _, err := httpapi.WriteJSONResponse(w, 400, result.StatusCode400()); err != nil {
			log.Print(err.Error())
		}
		return
	}
	if result.HasStatusCode500() {
		if _, err := httpapi.WriteJSONResponse(w, 500, result.StatusCode500()); err != nil {
			log.Print(err.Error())
		}
		return
	}
	ctrl.responseGetVersion500(w, errors.New("Unknown error"))
}

func (ctrl *capabilitiesController) responseGetVersion500(w http.ResponseWriter, rsp_err error) {
	result := gosnappi.NewGetVersionResponse()
	result.StatusCode500().SetErrors([]string{rsp_err.Error()})
	if _, err := httpapi.WriteJSONResponse(w, 500, result.StatusCode500()); err != nil {
		log.Print(err.Error())
	}
}
