// This file is autogenerated. Do not modify
package controllers

import (
	"errors"
	"io"
	"log"
	"net/http"

	gosnappi "github.com/open-traffic-generator/snappi/gosnappi"
	"github.com/open-traffic-generator/snappi/gosnappi/httpapi"
	"github.com/open-traffic-generator/snappi/gosnappi/httpapi/interfaces"
	"google.golang.org/protobuf/encoding/protojson"
)

type configurationController struct {
	handler interfaces.ConfigurationHandler
}

func NewHttpConfigurationController(handler interfaces.ConfigurationHandler) interfaces.ConfigurationController {
	return &configurationController{handler}
}

func (ctrl *configurationController) Routes() []httpapi.Route {
	return []httpapi.Route{
		{Path: "/config", Method: "POST", Name: "SetConfig", Handler: ctrl.SetConfig},
		{Path: "/config", Method: "GET", Name: "GetConfig", Handler: ctrl.GetConfig},
		{Path: "/config", Method: "PATCH", Name: "UpdateConfig", Handler: ctrl.UpdateConfig},
	}
}

/*
SetConfig: POST /config
Description: Sets configuration resources on the traffic generator.
*/
func (ctrl *configurationController) SetConfig(w http.ResponseWriter, r *http.Request) {
	var item gosnappi.Config
	if r.Body != nil {
		body, readError := io.ReadAll(r.Body)
		if body != nil {
			item = gosnappi.NewConfig()
			err := item.Unmarshal().FromJson(string(body))
			if err != nil {
				ctrl.responseSetConfigError(w, "validation", err)
				return
			}
		} else {
			ctrl.responseSetConfigError(w, "validation", readError)
			return
		}
	} else {
		bodyError := errors.New("Request does not have a body")
		ctrl.responseSetConfigError(w, "validation", bodyError)
		return
	}
	result, err := ctrl.handler.SetConfig(item, r)
	if err != nil {
		ctrl.responseSetConfigError(w, "internal", err)
		return
	}

	if result.HasWarning() {

		proto, err := result.Warning().Marshal().ToProto()
		if err != nil {
			ctrl.responseSetConfigError(w, "validation", err)
		}
		data, err := configurationMrlOpts.Marshal(proto)
		if err != nil {
			ctrl.responseSetConfigError(w, "validation", err)
		}
		httpapi.WriteCustomJSONResponse(w, 200, data)

		return
	}
	ctrl.responseSetConfigError(w, "internal", errors.New("Unknown error"))
}

func (ctrl *configurationController) responseSetConfigError(w http.ResponseWriter, errorKind gosnappi.ErrorKindEnum, rsp_err error) {
	var result gosnappi.Error
	var statusCode int32
	if errorKind == "validation" {
		statusCode = 400
	} else if errorKind == "internal" {
		statusCode = 500
	}

	if rErr, ok := rsp_err.(gosnappi.Error); ok {
		result = rErr
	} else {
		result = gosnappi.NewError()
		err := result.Unmarshal().FromJson(rsp_err.Error())
		if err != nil {
			_ = result.SetCode(statusCode)
			err = result.SetKind(errorKind)
			if err != nil {
				log.Print(err.Error())
			}
			_ = result.SetErrors([]string{rsp_err.Error()})
		}
	}

	if _, err := httpapi.WriteJSONResponse(w, int(result.Code()), result.Marshal()); err != nil {
		log.Print(err.Error())
	}
}

/*
GetConfig: GET /config
Description:
*/
func (ctrl *configurationController) GetConfig(w http.ResponseWriter, r *http.Request) {
	result, err := ctrl.handler.GetConfig(r)
	if err != nil {
		ctrl.responseGetConfigError(w, "internal", err)
		return
	}

	if result.HasConfig() {
		if _, err := httpapi.WriteJSONResponse(w, 200, result.Config().Marshal()); err != nil {
			log.Print(err.Error())
		}
		return
	}
	ctrl.responseGetConfigError(w, "internal", errors.New("Unknown error"))
}

func (ctrl *configurationController) responseGetConfigError(w http.ResponseWriter, errorKind gosnappi.ErrorKindEnum, rsp_err error) {
	var result gosnappi.Error
	var statusCode int32
	if errorKind == "validation" {
		statusCode = 400
	} else if errorKind == "internal" {
		statusCode = 500
	}

	if rErr, ok := rsp_err.(gosnappi.Error); ok {
		result = rErr
	} else {
		result = gosnappi.NewError()
		err := result.Unmarshal().FromJson(rsp_err.Error())
		if err != nil {
			_ = result.SetCode(statusCode)
			err = result.SetKind(errorKind)
			if err != nil {
				log.Print(err.Error())
			}
			_ = result.SetErrors([]string{rsp_err.Error()})
		}
	}

	if _, err := httpapi.WriteJSONResponse(w, int(result.Code()), result.Marshal()); err != nil {
		log.Print(err.Error())
	}
}

/*
UpdateConfig: PATCH /config
Description: Updates specific attributes of resources configured on the traffic generator. The fetched configuration shall reflect the updates applied successfully.
The Response.Warnings in the Success response is available for implementers to disclose additional information about a state change including any implicit changes that are outside the scope of the state change.
*/
func (ctrl *configurationController) UpdateConfig(w http.ResponseWriter, r *http.Request) {
	var item gosnappi.ConfigUpdate
	if r.Body != nil {
		body, readError := io.ReadAll(r.Body)
		if body != nil {
			item = gosnappi.NewConfigUpdate()
			err := item.Unmarshal().FromJson(string(body))
			if err != nil {
				ctrl.responseUpdateConfigError(w, "validation", err)
				return
			}
		} else {
			ctrl.responseUpdateConfigError(w, "validation", readError)
			return
		}
	} else {
		bodyError := errors.New("Request does not have a body")
		ctrl.responseUpdateConfigError(w, "validation", bodyError)
		return
	}
	result, err := ctrl.handler.UpdateConfig(item, r)
	if err != nil {
		ctrl.responseUpdateConfigError(w, "internal", err)
		return
	}

	if result.HasWarning() {
		if _, err := httpapi.WriteJSONResponse(w, 200, result.Warning().Marshal()); err != nil {
			log.Print(err.Error())
		}
		return
	}
	ctrl.responseUpdateConfigError(w, "internal", errors.New("Unknown error"))
}

func (ctrl *configurationController) responseUpdateConfigError(w http.ResponseWriter, errorKind gosnappi.ErrorKindEnum, rsp_err error) {
	var result gosnappi.Error
	var statusCode int32
	if errorKind == "validation" {
		statusCode = 400
	} else if errorKind == "internal" {
		statusCode = 500
	}

	if rErr, ok := rsp_err.(gosnappi.Error); ok {
		result = rErr
	} else {
		result = gosnappi.NewError()
		err := result.Unmarshal().FromJson(rsp_err.Error())
		if err != nil {
			_ = result.SetCode(statusCode)
			err = result.SetKind(errorKind)
			if err != nil {
				log.Print(err.Error())
			}
			_ = result.SetErrors([]string{rsp_err.Error()})
		}
	}

	if _, err := httpapi.WriteJSONResponse(w, int(result.Code()), result.Marshal()); err != nil {
		log.Print(err.Error())
	}
}

var configurationMrlOpts = protojson.MarshalOptions{
	UseProtoNames:   true,
	AllowPartial:    true,
	EmitUnpopulated: true,
	Indent:          "  ",
}
