// This file is autogenerated. Do not modify
package controllers

import (
	"errors"
	"io"
	"log"
	"net/http"

	gosnappi "github.com/open-traffic-generator/snappi/gosnappi"
	"github.com/open-traffic-generator/snappi/gosnappi/httpapi"
	"github.com/open-traffic-generator/snappi/gosnappi/httpapi/interfaces"
)

type monitorController struct {
	handler interfaces.MonitorHandler
}

func NewHttpMonitorController(handler interfaces.MonitorHandler) interfaces.MonitorController {
	return &monitorController{handler}
}

func (ctrl *monitorController) Routes() []httpapi.Route {
	return []httpapi.Route{
		{Path: "/monitor/metrics", Method: "POST", Name: "GetMetrics", Handler: ctrl.GetMetrics},
		{Path: "/monitor/states", Method: "POST", Name: "GetStates", Handler: ctrl.GetStates},
		{Path: "/monitor/capture", Method: "POST", Name: "GetCapture", Handler: ctrl.GetCapture},
	}
}

/*
GetMetrics: POST /monitor/metrics
Description:
*/
func (ctrl *monitorController) GetMetrics(w http.ResponseWriter, r *http.Request) {
	var item gosnappi.MetricsRequest
	if r.Body != nil {
		body, readError := io.ReadAll(r.Body)
		if body != nil {
			item = gosnappi.NewMetricsRequest()
			err := item.FromJson(string(body))
			if err != nil {
				ctrl.responseGetMetricsError(w, "validation", err)
				return
			}
		} else {
			ctrl.responseGetMetricsError(w, "validation", readError)
			return
		}
	} else {
		bodyError := errors.New("Request does not have a body")
		ctrl.responseGetMetricsError(w, "validation", bodyError)
		return
	}
	result, err := ctrl.handler.GetMetrics(item, r)
	if err != nil {
		ctrl.responseGetMetricsError(w, "internal", err)
		return
	}

	if result.HasMetricsResponse() {
		if _, err := httpapi.WriteJSONResponse(w, 200, result.MetricsResponse()); err != nil {
			log.Print(err.Error())
		}
		return
	}
	ctrl.responseGetMetricsError(w, "internal", errors.New("Unknown error"))
}

func (ctrl *monitorController) responseGetMetricsError(w http.ResponseWriter, errorKind gosnappi.ErrorKindEnum, rsp_err error) {
	var result gosnappi.Error
	var statusCode int32
	if errorKind == "validation" {
		statusCode = 400
	} else if errorKind == "internal" {
		statusCode = 500
	}

	if rErr, ok := rsp_err.(gosnappi.Error); ok {
		result = rErr
	} else {
		result = gosnappi.NewError()
		err := result.FromJson(rsp_err.Error())
		if err != nil {
			result.Msg().Code = statusCode
			err = result.SetKind(errorKind)
			if err != nil {
				log.Print(err.Error())
			}
			result.Msg().Errors = []string{rsp_err.Error()}
		}
	}

	if _, err := httpapi.WriteJSONResponse(w, int(result.Code()), result); err != nil {
		log.Print(err.Error())
	}
}

/*
GetStates: POST /monitor/states
Description:
*/
func (ctrl *monitorController) GetStates(w http.ResponseWriter, r *http.Request) {
	var item gosnappi.StatesRequest
	if r.Body != nil {
		body, readError := io.ReadAll(r.Body)
		if body != nil {
			item = gosnappi.NewStatesRequest()
			err := item.FromJson(string(body))
			if err != nil {
				ctrl.responseGetStatesError(w, "validation", err)
				return
			}
		} else {
			ctrl.responseGetStatesError(w, "validation", readError)
			return
		}
	} else {
		bodyError := errors.New("Request does not have a body")
		ctrl.responseGetStatesError(w, "validation", bodyError)
		return
	}
	result, err := ctrl.handler.GetStates(item, r)
	if err != nil {
		ctrl.responseGetStatesError(w, "internal", err)
		return
	}

	if result.HasStatesResponse() {
		if _, err := httpapi.WriteJSONResponse(w, 200, result.StatesResponse()); err != nil {
			log.Print(err.Error())
		}
		return
	}
	ctrl.responseGetStatesError(w, "internal", errors.New("Unknown error"))
}

func (ctrl *monitorController) responseGetStatesError(w http.ResponseWriter, errorKind gosnappi.ErrorKindEnum, rsp_err error) {
	var result gosnappi.Error
	var statusCode int32
	if errorKind == "validation" {
		statusCode = 400
	} else if errorKind == "internal" {
		statusCode = 500
	}

	if rErr, ok := rsp_err.(gosnappi.Error); ok {
		result = rErr
	} else {
		result = gosnappi.NewError()
		err := result.FromJson(rsp_err.Error())
		if err != nil {
			result.Msg().Code = statusCode
			err = result.SetKind(errorKind)
			if err != nil {
				log.Print(err.Error())
			}
			result.Msg().Errors = []string{rsp_err.Error()}
		}
	}

	if _, err := httpapi.WriteJSONResponse(w, int(result.Code()), result); err != nil {
		log.Print(err.Error())
	}
}

/*
GetCapture: POST /monitor/capture
Description:
*/
func (ctrl *monitorController) GetCapture(w http.ResponseWriter, r *http.Request) {
	var item gosnappi.CaptureRequest
	if r.Body != nil {
		body, readError := io.ReadAll(r.Body)
		if body != nil {
			item = gosnappi.NewCaptureRequest()
			err := item.FromJson(string(body))
			if err != nil {
				ctrl.responseGetCaptureError(w, "validation", err)
				return
			}
		} else {
			ctrl.responseGetCaptureError(w, "validation", readError)
			return
		}
	} else {
		bodyError := errors.New("Request does not have a body")
		ctrl.responseGetCaptureError(w, "validation", bodyError)
		return
	}
	result, err := ctrl.handler.GetCapture(item, r)
	if err != nil {
		ctrl.responseGetCaptureError(w, "internal", err)
		return
	}

	if result.HasResponseBytes() {
		if _, err := httpapi.WriteByteResponse(w, 200, result.ResponseBytes()); err != nil {
			log.Print(err.Error())
		}
		return
	}
	ctrl.responseGetCaptureError(w, "internal", errors.New("Unknown error"))
}

func (ctrl *monitorController) responseGetCaptureError(w http.ResponseWriter, errorKind gosnappi.ErrorKindEnum, rsp_err error) {
	var result gosnappi.Error
	var statusCode int32
	if errorKind == "validation" {
		statusCode = 400
	} else if errorKind == "internal" {
		statusCode = 500
	}

	if rErr, ok := rsp_err.(gosnappi.Error); ok {
		result = rErr
	} else {
		result = gosnappi.NewError()
		err := result.FromJson(rsp_err.Error())
		if err != nil {
			result.Msg().Code = statusCode
			err = result.SetKind(errorKind)
			if err != nil {
				log.Print(err.Error())
			}
			result.Msg().Errors = []string{rsp_err.Error()}
		}
	}

	if _, err := httpapi.WriteJSONResponse(w, int(result.Code()), result); err != nil {
		log.Print(err.Error())
	}
}
