// This file is autogenerated. Do not modify
package interfaces

import (
	"net/http"

	gosnappi "github.com/open-traffic-generator/snappi/gosnappi"
	"github.com/open-traffic-generator/snappi/gosnappi/httpapi"
)

type CapabilitiesController interface {
	Routes() []httpapi.Route
	GetVersion(w http.ResponseWriter, r *http.Request)
}

type CapabilitiesHandler interface {
	GetController() CapabilitiesController
	/*
		GetVersion: GET /capabilities/version
		Description:
	*/
	GetVersion(r *http.Request) (gosnappi.GetVersionResponse, error)
}
