// This file is autogenerated. Do not modify
package interfaces

import (
	"net/http"
	"github.com/open-traffic-generator/snappi/gosnappi/httpapi"
	gosnappi "github.com/open-traffic-generator/snappi/gosnappi"
)

type CaptureController interface {
	Routes() []httpapi.Route
	GetCapture(w http.ResponseWriter, r *http.Request)
}

type CaptureHandler interface {
	GetController() CaptureController
	/*
	GetCapture: POST /results/capture
	Description: 
	*/
	GetCapture(rbody gosnappi.CaptureRequest, r *http.Request) gosnappi.GetCaptureResponse
}

