// This file is autogenerated. Do not modify
package interfaces

import (
	"net/http"

	gosnappi "github.com/open-traffic-generator/snappi/gosnappi"
	"github.com/open-traffic-generator/snappi/gosnappi/httpapi"
)

type ConfigurationController interface {
	Routes() []httpapi.Route
	SetConfig(w http.ResponseWriter, r *http.Request)
	GetConfig(w http.ResponseWriter, r *http.Request)
	UpdateConfig(w http.ResponseWriter, r *http.Request)
}

type ConfigurationHandler interface {
	GetController() ConfigurationController
	/*
		SetConfig: POST /config
		Description: Sets configuration resources on the traffic generator.
	*/
	SetConfig(rbody gosnappi.Config, r *http.Request) (gosnappi.SetConfigResponse, error)
	/*
		GetConfig: GET /config
		Description:
	*/
	GetConfig(r *http.Request) (gosnappi.GetConfigResponse, error)
	/*
			UpdateConfig: PATCH /config
			Description: Updates specific attributes of resources configured on the traffic generator. The fetched configuration shall reflect the updates applied successfully.
		The Response.Warnings in the Success response is available for implementers to disclose additional information about a state change including any implicit changes that are outside the scope of the state change.
	*/
	UpdateConfig(rbody gosnappi.ConfigUpdate, r *http.Request) (gosnappi.UpdateConfigResponse, error)
}
