// This file is autogenerated. Do not modify
package interfaces

import (
	"net/http"
	"github.com/open-traffic-generator/snappi/gosnappi/httpapi"
	gosnappi "github.com/open-traffic-generator/snappi/gosnappi"
)

type ConfigurationController interface {
	Routes() []httpapi.Route
	SetConfig(w http.ResponseWriter, r *http.Request)
	GetConfig(w http.ResponseWriter, r *http.Request)
}

type ConfigurationHandler interface {
	GetController() ConfigurationController
	/*
	SetConfig: POST /config
	Description: Sets configuration resources on the traffic generator.
	*/
	SetConfig(rbody gosnappi.Config, r *http.Request) gosnappi.SetConfigResponse
	/*
	GetConfig: GET /config
	Description: 
	*/
	GetConfig(r *http.Request) gosnappi.GetConfigResponse
}

