// This file is autogenerated. Do not modify
package interfaces

import (
	"net/http"

	gosnappi "github.com/open-traffic-generator/snappi/gosnappi"
	"github.com/open-traffic-generator/snappi/gosnappi/httpapi"
)

type ControlController interface {
	Routes() []httpapi.Route
	SetControlState(w http.ResponseWriter, r *http.Request)
	SetControlAction(w http.ResponseWriter, r *http.Request)
}

type ControlHandler interface {
	GetController() ControlController
	/*
		SetControlState: POST /control/state
		Description: Sets the operational state of configured resources.
	*/
	SetControlState(rbody gosnappi.ControlState, r *http.Request) (gosnappi.SetControlStateResponse, error)
	/*
		SetControlAction: POST /control/action
		Description: Triggers actions against configured resources.
	*/
	SetControlAction(rbody gosnappi.ControlAction, r *http.Request) (gosnappi.SetControlActionResponse, error)
}
