// This file is autogenerated. Do not modify
package interfaces

import (
	"net/http"

	gosnappi "github.com/open-traffic-generator/snappi/gosnappi"
	"github.com/open-traffic-generator/snappi/gosnappi/httpapi"
)

type MetricsController interface {
	Routes() []httpapi.Route
	GetMetrics(w http.ResponseWriter, r *http.Request)
}

type MetricsHandler interface {
	GetController() MetricsController
	/*
		GetMetrics: POST /results/metrics
		Description:
	*/
	GetMetrics(rbody gosnappi.MetricsRequest, r *http.Request) gosnappi.GetMetricsResponse
}
