// This file is autogenerated. Do not modify
package interfaces

import (
	"net/http"

	gosnappi "github.com/open-traffic-generator/snappi/gosnappi"
	"github.com/open-traffic-generator/snappi/gosnappi/httpapi"
)

type MonitorController interface {
	Routes() []httpapi.Route
	GetMetrics(w http.ResponseWriter, r *http.Request)
	GetStates(w http.ResponseWriter, r *http.Request)
	GetCapture(w http.ResponseWriter, r *http.Request)
}

type MonitorHandler interface {
	GetController() MonitorController
	/*
		GetMetrics: POST /monitor/metrics
		Description:
	*/
	GetMetrics(rbody gosnappi.MetricsRequest, r *http.Request) (gosnappi.GetMetricsResponse, error)
	/*
		GetStates: POST /monitor/states
		Description:
	*/
	GetStates(rbody gosnappi.StatesRequest, r *http.Request) (gosnappi.GetStatesResponse, error)
	/*
		GetCapture: POST /monitor/capture
		Description:
	*/
	GetCapture(rbody gosnappi.CaptureRequest, r *http.Request) (gosnappi.GetCaptureResponse, error)
}
