// This file is autogenerated. Do not modify
package interfaces

import (
	"net/http"

	gosnappi "github.com/open-traffic-generator/snappi/gosnappi"
	"github.com/open-traffic-generator/snappi/gosnappi/httpapi"
)

type StatesController interface {
	Routes() []httpapi.Route
	GetStates(w http.ResponseWriter, r *http.Request)
}

type StatesHandler interface {
	GetController() StatesController
	/*
		GetStates: POST /results/states
		Description:
	*/
	GetStates(rbody gosnappi.StatesRequest, r *http.Request) gosnappi.GetStatesResponse
}
